# Generated by Django 3.2 on 2022-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220208_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_additional_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
