# Generated by Django 3.2 on 2022-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_default_additional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_additional_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
