# Generated by Django 3.2 on 2022-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_default_additional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(default='', editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
