# Generated by Django 3.2 on 2022-01-28 14:35

from decimal import Decimal
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220128_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field= models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),

    ]
