# Generated by Django 3.2.5 on 2022-03-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_delete_resendemail'),
        ('store', '0010_product_has_sizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='MusicProduct',
        ),
    ]
