# Generated by Django 3.2.5 on 2022-03-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_product_musicproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicproduct',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='musicproduct',
            name='image_alt',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
