# Generated by Django 3.2.5 on 2022-03-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_subscriptionlineitem_subscribed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='order_total',
        ),
    ]
