# Generated by Django 3.2.5 on 2022-03-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
        ('profiles', '0010_userprofile_user'),
        ('checkout', '0010_remove_subscribedcustomer_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcustomer',
            name='customer',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='djstripe.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribedcustomer',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
