# Generated by Django 3.2.5 on 2022-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20220310_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='original_lesson_bag',
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='original_lesson_bag',
            field=models.TextField(default=''),
        ),
    ]
