# Generated by Django 3.2.5 on 2022-03-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20220310_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='subscription_name',
            field=models.CharField(default='', editable=False, max_length=350),
            preserve_default=False,
        ),
    ]
