# Generated by Django 3.2.5 on 2022-03-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
        ('checkout', '0014_subscriptionlineitem_subscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='county',
        ),
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='town_or_city',
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='end_date',
            field=models.CharField(default=1, editable=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='latest_invoice',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoice', to='djstripe.invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='start_date',
            field=models.CharField(default=1, editable=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='status',
            field=models.CharField(default=1, editable=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='student',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
