# Generated by Django 3.2.5 on 2022-03-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userprofile_user'),
        ('djstripe', '0010_alter_customer_balance'),
        ('checkout', '0017_alter_subscriptionlineitem_latest_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcustomer',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djstripe.customer'),
        ),
        migrations.AlterField(
            model_name='subscribedcustomer',
            name='subscribed_customer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subscribedcustomer',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_customer', to='checkout.subscribedcustomer'),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='end_date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='latest_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoice', to='djstripe.invoice'),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='start_date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='status',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='subscribed_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_lineitems', to='djstripe.subscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='subscription_name',
            field=models.CharField(max_length=350),
        ),
    ]
