# Generated by Django 3.2.5 on 2022-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_rename_subscription_subscriptionlineitem_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='subscription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
