# Generated by Django 3.2.5 on 2022-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_alter_subscriptionlineitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
