# Generated by Django 3.2.5 on 2022-03-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userprofile_user'),
        ('checkout', '0024_auto_20220315_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedcustomer',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_customers', to='profiles.userprofile'),
        ),
    ]
