# Generated by Django 3.2 on 2022-01-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
