# Generated by Django 3.2 on 2022-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quote', models.CharField(max_length=250)),
                ('page', models.CharField(default='home', max_length=15)),
            ],
            options={
                'ordering': ['page'],
            },
        ),
    ]
