# Generated by Django 3.2.5 on 2022-03-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
    ]
