# Generated by Django 3.2.5 on 2022-03-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
        ('home', '0011_alter_user_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.customer'),
        ),
    ]
