# Generated by Django 3.2.5 on 2022-03-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_userlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlineitem',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
