# Generated by Django 3.2.5 on 2022-03-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220310_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlineitem',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='userlineitem',
            name='subscription_user_id',
            field=models.CharField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
