# Generated by Django 3.2.5 on 2022-03-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
        ('home', '0016_auto_20220310_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLineItem',
            new_name='UserSubscription',
        ),
    ]
