# Generated by Django 3.2.5 on 2022-03-13 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
        ('home', '0017_rename_userlineitem_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_name',
            field=models.CharField(blank=True, editable=False, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_user_id',
            field=models.CharField(blank=True, editable=False, max_length=350, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='username',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userlineitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
