# Generated by Django 3.2.5 on 2022-03-18 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220313_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='deletable',
        ),
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
