# Generated by Django 3.2.5 on 2022-03-18 17:23

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_contact_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='placeholder', max_length=80, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_name', models.CharField(blank=True, default='placeholder', max_length=100)),
                ('video_url', embed_video.fields.EmbedVideoField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subscribed_student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userstudent', to='home.usersubscription')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
