# Generated by Django 3.2.5 on 2022-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_studentshowcase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentshowcase',
            options={'ordering': ['date'], 'verbose_name_plural': 'Student Showcase'},
        ),
        migrations.AlterField(
            model_name='studentshowcase',
            name='subscribed_student',
            field=models.CharField(default='student_subscription', max_length=80, unique=True),
        ),
    ]
