# Generated by Django 3.2.5 on 2022-03-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_studentshowcase_subscribed_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='home.user'),
            preserve_default=False,
        ),
    ]
