# Generated by Django 3.2.5 on 2022-03-21 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_alter_customer_balance'),
        ('home', '0025_contact_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentshowcase',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='showcase_customer', to='djstripe.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentshowcase',
            name='subscription',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='showcase_subscription', to='djstripe.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
