# Generated by Django 3.2.5 on 2022-03-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220321_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentshowcase',
            options={'get_latest_by': ['date'], 'ordering': ['date'], 'verbose_name_plural': 'Student Showcase'},
        ),
        migrations.RemoveField(
            model_name='studentshowcase',
            name='image',
        ),
    ]
