# Generated by Django 3.2.5 on 2022-03-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_contact_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
