# Generated by Django 3.2.5 on 2022-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_user_marketing_opt_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=80)),
                ('last_name', models.CharField(default='last name', max_length=80)),
                ('email', models.EmailField(default='email address', max_length=150)),
                ('marketing_opt_in', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Marketing Sign Up Customers',
                'ordering': ['date'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='marketing_opt_in',
        ),
    ]
