# Generated by Django 3.2 on 2022-03-01 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0007_alter_subscribeduser_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeduser',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribeduser',
            name='username',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='subscription_type',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_type', to='lessons.subscription'),
        ),
    ]
