# Generated by Django 3.2.5 on 2022-03-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20220301_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeduser',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='subscribeduser',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='subscribeduser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='SubscribedUser',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
