# Generated by Django 3.2.5 on 2022-03-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_subscribedcustomer_subscriptionlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='subscribedcustomer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='subscriptionlineitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='subscriptionlineitem',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='subscriptionlineitem',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='SubscribedCustomer',
        ),
        migrations.DeleteModel(
            name='SubscriptionLineItem',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
